<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // United States - Most popular
            [
                'code' => 'US',
                'code_alpha3' => 'USA',
                'numeric_code' => '840',
                'name' => 'United States',
                'native_name' => json_encode(['eng' => 'United States']),
                'capital' => 'Washington, D.C.',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'currency_code' => 'USD',
                'currency_name' => 'United States Dollar',
                'currency_symbol' => '$',
                'phone_code' => '+1',
                'flag_emoji' => '🇺🇸',
                'flag_svg' => 'https://flagcdn.com/us.svg',
                'languages' => json_encode(['eng']),
                'tld' => '.us',
                'latitude' => 37.0902,
                'longitude' => -95.7129,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 1,
                'metadata' => json_encode(['area' => 9833520, 'population' => 331002651]),
            ],
            // United Kingdom
            [
                'code' => 'GB',
                'code_alpha3' => 'GBR',
                'numeric_code' => '826',
                'name' => 'United Kingdom',
                'native_name' => json_encode(['eng' => 'United Kingdom']),
                'capital' => 'London',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'GBP',
                'currency_name' => 'British Pound Sterling',
                'currency_symbol' => '£',
                'phone_code' => '+44',
                'flag_emoji' => '🇬🇧',
                'flag_svg' => 'https://flagcdn.com/gb.svg',
                'languages' => json_encode(['eng']),
                'tld' => '.uk',
                'latitude' => 55.3781,
                'longitude' => -3.4360,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 2,
                'metadata' => json_encode(['area' => 242900, 'population' => 67886011]),
            ],
            // Canada
            [
                'code' => 'CA',
                'code_alpha3' => 'CAN',
                'numeric_code' => '124',
                'name' => 'Canada',
                'native_name' => json_encode(['eng' => 'Canada', 'fra' => 'Canada']),
                'capital' => 'Ottawa',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'currency_code' => 'CAD',
                'currency_name' => 'Canadian Dollar',
                'currency_symbol' => '$',
                'phone_code' => '+1',
                'flag_emoji' => '🇨🇦',
                'flag_svg' => 'https://flagcdn.com/ca.svg',
                'languages' => json_encode(['eng', 'fra']),
                'tld' => '.ca',
                'latitude' => 56.1304,
                'longitude' => -106.3468,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 3,
                'metadata' => json_encode(['area' => 9984670, 'population' => 37742154]),
            ],
            // Australia
            [
                'code' => 'AU',
                'code_alpha3' => 'AUS',
                'numeric_code' => '036',
                'name' => 'Australia',
                'native_name' => json_encode(['eng' => 'Australia']),
                'capital' => 'Canberra',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'currency_code' => 'AUD',
                'currency_name' => 'Australian Dollar',
                'currency_symbol' => '$',
                'phone_code' => '+61',
                'flag_emoji' => '🇦🇺',
                'flag_svg' => 'https://flagcdn.com/au.svg',
                'languages' => json_encode(['eng']),
                'tld' => '.au',
                'latitude' => -25.2744,
                'longitude' => 133.7751,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 4,
                'metadata' => json_encode(['area' => 7692024, 'population' => 25499884]),
            ],
            // Germany
            [
                'code' => 'DE',
                'code_alpha3' => 'DEU',
                'numeric_code' => '276',
                'name' => 'Germany',
                'native_name' => json_encode(['deu' => 'Deutschland']),
                'capital' => 'Berlin',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+49',
                'flag_emoji' => '🇩🇪',
                'flag_svg' => 'https://flagcdn.com/de.svg',
                'languages' => json_encode(['deu']),
                'tld' => '.de',
                'latitude' => 51.1657,
                'longitude' => 10.4515,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 5,
                'metadata' => json_encode(['area' => 357114, 'population' => 83783942]),
            ],
            // France
            [
                'code' => 'FR',
                'code_alpha3' => 'FRA',
                'numeric_code' => '250',
                'name' => 'France',
                'native_name' => json_encode(['fra' => 'France']),
                'capital' => 'Paris',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+33',
                'flag_emoji' => '🇫🇷',
                'flag_svg' => 'https://flagcdn.com/fr.svg',
                'languages' => json_encode(['fra']),
                'tld' => '.fr',
                'latitude' => 46.2276,
                'longitude' => 2.2137,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 6,
                'metadata' => json_encode(['area' => 551695, 'population' => 67391582]),
            ],
            // Spain
            [
                'code' => 'ES',
                'code_alpha3' => 'ESP',
                'numeric_code' => '724',
                'name' => 'Spain',
                'native_name' => json_encode(['spa' => 'España']),
                'capital' => 'Madrid',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+34',
                'flag_emoji' => '🇪🇸',
                'flag_svg' => 'https://flagcdn.com/es.svg',
                'languages' => json_encode(['spa']),
                'tld' => '.es',
                'latitude' => 40.4637,
                'longitude' => -3.7492,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 7,
                'metadata' => json_encode(['area' => 505992, 'population' => 47351567]),
            ],
            // Italy
            [
                'code' => 'IT',
                'code_alpha3' => 'ITA',
                'numeric_code' => '380',
                'name' => 'Italy',
                'native_name' => json_encode(['ita' => 'Italia']),
                'capital' => 'Rome',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+39',
                'flag_emoji' => '🇮🇹',
                'flag_svg' => 'https://flagcdn.com/it.svg',
                'languages' => json_encode(['ita']),
                'tld' => '.it',
                'latitude' => 41.8719,
                'longitude' => 12.5674,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 8,
                'metadata' => json_encode(['area' => 301336, 'population' => 60461826]),
            ],
            // Japan
            [
                'code' => 'JP',
                'code_alpha3' => 'JPN',
                'numeric_code' => '392',
                'name' => 'Japan',
                'native_name' => json_encode(['jpn' => '日本']),
                'capital' => 'Tokyo',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'JPY',
                'currency_name' => 'Japanese Yen',
                'currency_symbol' => '¥',
                'phone_code' => '+81',
                'flag_emoji' => '🇯🇵',
                'flag_svg' => 'https://flagcdn.com/jp.svg',
                'languages' => json_encode(['jpn']),
                'tld' => '.jp',
                'latitude' => 36.2048,
                'longitude' => 138.2529,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 9,
                'metadata' => json_encode(['area' => 377930, 'population' => 126476461]),
            ],
            // China
            [
                'code' => 'CN',
                'code_alpha3' => 'CHN',
                'numeric_code' => '156',
                'name' => 'China',
                'native_name' => json_encode(['zho' => '中国']),
                'capital' => 'Beijing',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'CNY',
                'currency_name' => 'Chinese Yuan',
                'currency_symbol' => '¥',
                'phone_code' => '+86',
                'flag_emoji' => '🇨🇳',
                'flag_svg' => 'https://flagcdn.com/cn.svg',
                'languages' => json_encode(['zho']),
                'tld' => '.cn',
                'latitude' => 35.8617,
                'longitude' => 104.1954,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 10,
                'metadata' => json_encode(['area' => 9706961, 'population' => 1439323776]),
            ],
            // India
            [
                'code' => 'IN',
                'code_alpha3' => 'IND',
                'numeric_code' => '356',
                'name' => 'India',
                'native_name' => json_encode(['hin' => 'भारत', 'eng' => 'India']),
                'capital' => 'New Delhi',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'INR',
                'currency_name' => 'Indian Rupee',
                'currency_symbol' => '₹',
                'phone_code' => '+91',
                'flag_emoji' => '🇮🇳',
                'flag_svg' => 'https://flagcdn.com/in.svg',
                'languages' => json_encode(['hin', 'eng']),
                'tld' => '.in',
                'latitude' => 20.5937,
                'longitude' => 78.9629,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 11,
                'metadata' => json_encode(['area' => 3287590, 'population' => 1380004385]),
            ],
            // Brazil
            [
                'code' => 'BR',
                'code_alpha3' => 'BRA',
                'numeric_code' => '076',
                'name' => 'Brazil',
                'native_name' => json_encode(['por' => 'Brasil']),
                'capital' => 'Brasília',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'BRL',
                'currency_name' => 'Brazilian Real',
                'currency_symbol' => 'R$',
                'phone_code' => '+55',
                'flag_emoji' => '🇧🇷',
                'flag_svg' => 'https://flagcdn.com/br.svg',
                'languages' => json_encode(['por']),
                'tld' => '.br',
                'latitude' => -14.2350,
                'longitude' => -51.9253,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 12,
                'metadata' => json_encode(['area' => 8515767, 'population' => 212559417]),
            ],
            // Mexico
            [
                'code' => 'MX',
                'code_alpha3' => 'MEX',
                'numeric_code' => '484',
                'name' => 'Mexico',
                'native_name' => json_encode(['spa' => 'México']),
                'capital' => 'Mexico City',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'currency_code' => 'MXN',
                'currency_name' => 'Mexican Peso',
                'currency_symbol' => '$',
                'phone_code' => '+52',
                'flag_emoji' => '🇲🇽',
                'flag_svg' => 'https://flagcdn.com/mx.svg',
                'languages' => json_encode(['spa']),
                'tld' => '.mx',
                'latitude' => 23.6345,
                'longitude' => -102.5528,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 13,
                'metadata' => json_encode(['area' => 1964375, 'population' => 128932753]),
            ],
            // Netherlands
            [
                'code' => 'NL',
                'code_alpha3' => 'NLD',
                'numeric_code' => '528',
                'name' => 'Netherlands',
                'native_name' => json_encode(['nld' => 'Nederland']),
                'capital' => 'Amsterdam',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+31',
                'flag_emoji' => '🇳🇱',
                'flag_svg' => 'https://flagcdn.com/nl.svg',
                'languages' => json_encode(['nld']),
                'tld' => '.nl',
                'latitude' => 52.1326,
                'longitude' => 5.2913,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 14,
                'metadata' => json_encode(['area' => 41850, 'population' => 17134872]),
            ],
            // Switzerland
            [
                'code' => 'CH',
                'code_alpha3' => 'CHE',
                'numeric_code' => '756',
                'name' => 'Switzerland',
                'native_name' => json_encode(['deu' => 'Schweiz', 'fra' => 'Suisse', 'ita' => 'Svizzera']),
                'capital' => 'Bern',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'CHF',
                'currency_name' => 'Swiss Franc',
                'currency_symbol' => 'Fr',
                'phone_code' => '+41',
                'flag_emoji' => '🇨🇭',
                'flag_svg' => 'https://flagcdn.com/ch.svg',
                'languages' => json_encode(['deu', 'fra', 'ita']),
                'tld' => '.ch',
                'latitude' => 46.8182,
                'longitude' => 8.2275,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 15,
                'metadata' => json_encode(['area' => 41284, 'population' => 8654622]),
            ],
            // Sweden
            [
                'code' => 'SE',
                'code_alpha3' => 'SWE',
                'numeric_code' => '752',
                'name' => 'Sweden',
                'native_name' => json_encode(['swe' => 'Sverige']),
                'capital' => 'Stockholm',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'SEK',
                'currency_name' => 'Swedish Krona',
                'currency_symbol' => 'kr',
                'phone_code' => '+46',
                'flag_emoji' => '🇸🇪',
                'flag_svg' => 'https://flagcdn.com/se.svg',
                'languages' => json_encode(['swe']),
                'tld' => '.se',
                'latitude' => 60.1282,
                'longitude' => 18.6435,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 16,
                'metadata' => json_encode(['area' => 450295, 'population' => 10353442]),
            ],
            // Norway
            [
                'code' => 'NO',
                'code_alpha3' => 'NOR',
                'numeric_code' => '578',
                'name' => 'Norway',
                'native_name' => json_encode(['nor' => 'Norge']),
                'capital' => 'Oslo',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'NOK',
                'currency_name' => 'Norwegian Krone',
                'currency_symbol' => 'kr',
                'phone_code' => '+47',
                'flag_emoji' => '🇳🇴',
                'flag_svg' => 'https://flagcdn.com/no.svg',
                'languages' => json_encode(['nor']),
                'tld' => '.no',
                'latitude' => 60.4720,
                'longitude' => 8.4689,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 17,
                'metadata' => json_encode(['area' => 323802, 'population' => 5421241]),
            ],
            // Denmark
            [
                'code' => 'DK',
                'code_alpha3' => 'DNK',
                'numeric_code' => '208',
                'name' => 'Denmark',
                'native_name' => json_encode(['dan' => 'Danmark']),
                'capital' => 'Copenhagen',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'DKK',
                'currency_name' => 'Danish Krone',
                'currency_symbol' => 'kr',
                'phone_code' => '+45',
                'flag_emoji' => '🇩🇰',
                'flag_svg' => 'https://flagcdn.com/dk.svg',
                'languages' => json_encode(['dan']),
                'tld' => '.dk',
                'latitude' => 56.2639,
                'longitude' => 9.5018,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 18,
                'metadata' => json_encode(['area' => 42933, 'population' => 5831404]),
            ],
            // Poland
            [
                'code' => 'PL',
                'code_alpha3' => 'POL',
                'numeric_code' => '616',
                'name' => 'Poland',
                'native_name' => json_encode(['pol' => 'Polska']),
                'capital' => 'Warsaw',
                'region' => 'Europe',
                'subregion' => 'Central Europe',
                'currency_code' => 'PLN',
                'currency_name' => 'Polish Zloty',
                'currency_symbol' => 'zł',
                'phone_code' => '+48',
                'flag_emoji' => '🇵🇱',
                'flag_svg' => 'https://flagcdn.com/pl.svg',
                'languages' => json_encode(['pol']),
                'tld' => '.pl',
                'latitude' => 51.9194,
                'longitude' => 19.1451,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 19,
                'metadata' => json_encode(['area' => 312696, 'population' => 37846611]),
            ],
            // Belgium
            [
                'code' => 'BE',
                'code_alpha3' => 'BEL',
                'numeric_code' => '056',
                'name' => 'Belgium',
                'native_name' => json_encode(['nld' => 'België', 'fra' => 'Belgique', 'deu' => 'Belgien']),
                'capital' => 'Brussels',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+32',
                'flag_emoji' => '🇧🇪',
                'flag_svg' => 'https://flagcdn.com/be.svg',
                'languages' => json_encode(['nld', 'fra', 'deu']),
                'tld' => '.be',
                'latitude' => 50.5039,
                'longitude' => 4.4699,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 20,
                'metadata' => json_encode(['area' => 30528, 'population' => 11589623]),
            ],
            // Austria
            [
                'code' => 'AT',
                'code_alpha3' => 'AUT',
                'numeric_code' => '040',
                'name' => 'Austria',
                'native_name' => json_encode(['deu' => 'Österreich']),
                'capital' => 'Vienna',
                'region' => 'Europe',
                'subregion' => 'Central Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+43',
                'flag_emoji' => '🇦🇹',
                'flag_svg' => 'https://flagcdn.com/at.svg',
                'languages' => json_encode(['deu']),
                'tld' => '.at',
                'latitude' => 47.5162,
                'longitude' => 14.5501,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 21,
                'metadata' => json_encode(['area' => 83871, 'population' => 9006398]),
            ],
            // Portugal
            [
                'code' => 'PT',
                'code_alpha3' => 'PRT',
                'numeric_code' => '620',
                'name' => 'Portugal',
                'native_name' => json_encode(['por' => 'Portugal']),
                'capital' => 'Lisbon',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+351',
                'flag_emoji' => '🇵🇹',
                'flag_svg' => 'https://flagcdn.com/pt.svg',
                'languages' => json_encode(['por']),
                'tld' => '.pt',
                'latitude' => 39.3999,
                'longitude' => -8.2245,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 22,
                'metadata' => json_encode(['area' => 92090, 'population' => 10196709]),
            ],
            // Greece
            [
                'code' => 'GR',
                'code_alpha3' => 'GRC',
                'numeric_code' => '300',
                'name' => 'Greece',
                'native_name' => json_encode(['ell' => 'Ελλάδα']),
                'capital' => 'Athens',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+30',
                'flag_emoji' => '🇬🇷',
                'flag_svg' => 'https://flagcdn.com/gr.svg',
                'languages' => json_encode(['ell']),
                'tld' => '.gr',
                'latitude' => 39.0742,
                'longitude' => 21.8243,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 23,
                'metadata' => json_encode(['area' => 131990, 'population' => 10423054]),
            ],
            // Ireland
            [
                'code' => 'IE',
                'code_alpha3' => 'IRL',
                'numeric_code' => '372',
                'name' => 'Ireland',
                'native_name' => json_encode(['eng' => 'Ireland', 'gle' => 'Éire']),
                'capital' => 'Dublin',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'EUR',
                'currency_name' => 'Euro',
                'currency_symbol' => '€',
                'phone_code' => '+353',
                'flag_emoji' => '🇮🇪',
                'flag_svg' => 'https://flagcdn.com/ie.svg',
                'languages' => json_encode(['eng', 'gle']),
                'tld' => '.ie',
                'latitude' => 53.4129,
                'longitude' => -8.2439,
                'is_active' => true,
                'is_eu_member' => true,
                'display_order' => 24,
                'metadata' => json_encode(['area' => 70273, 'population' => 4937786]),
            ],
            // South Korea
            [
                'code' => 'KR',
                'code_alpha3' => 'KOR',
                'numeric_code' => '410',
                'name' => 'South Korea',
                'native_name' => json_encode(['kor' => '대한민국']),
                'capital' => 'Seoul',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'KRW',
                'currency_name' => 'South Korean Won',
                'currency_symbol' => '₩',
                'phone_code' => '+82',
                'flag_emoji' => '🇰🇷',
                'flag_svg' => 'https://flagcdn.com/kr.svg',
                'languages' => json_encode(['kor']),
                'tld' => '.kr',
                'latitude' => 35.9078,
                'longitude' => 127.7669,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 25,
                'metadata' => json_encode(['area' => 100210, 'population' => 51269185]),
            ],
            // Singapore
            [
                'code' => 'SG',
                'code_alpha3' => 'SGP',
                'numeric_code' => '702',
                'name' => 'Singapore',
                'native_name' => json_encode(['eng' => 'Singapore', 'zho' => '新加坡', 'msa' => 'Singapura', 'tam' => 'சிங்கப்பூர்']),
                'capital' => 'Singapore',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'SGD',
                'currency_name' => 'Singapore Dollar',
                'currency_symbol' => '$',
                'phone_code' => '+65',
                'flag_emoji' => '🇸🇬',
                'flag_svg' => 'https://flagcdn.com/sg.svg',
                'languages' => json_encode(['eng', 'zho', 'msa', 'tam']),
                'tld' => '.sg',
                'latitude' => 1.3521,
                'longitude' => 103.8198,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 26,
                'metadata' => json_encode(['area' => 710, 'population' => 5850342]),
            ],
            // New Zealand
            [
                'code' => 'NZ',
                'code_alpha3' => 'NZL',
                'numeric_code' => '554',
                'name' => 'New Zealand',
                'native_name' => json_encode(['eng' => 'New Zealand', 'mri' => 'Aotearoa']),
                'capital' => 'Wellington',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'currency_code' => 'NZD',
                'currency_name' => 'New Zealand Dollar',
                'currency_symbol' => '$',
                'phone_code' => '+64',
                'flag_emoji' => '🇳🇿',
                'flag_svg' => 'https://flagcdn.com/nz.svg',
                'languages' => json_encode(['eng', 'mri']),
                'tld' => '.nz',
                'latitude' => -40.9006,
                'longitude' => 174.8860,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 27,
                'metadata' => json_encode(['area' => 270467, 'population' => 5084300]),
            ],
            // Russia
            [
                'code' => 'RU',
                'code_alpha3' => 'RUS',
                'numeric_code' => '643',
                'name' => 'Russia',
                'native_name' => json_encode(['rus' => 'Россия']),
                'capital' => 'Moscow',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'RUB',
                'currency_name' => 'Russian Ruble',
                'currency_symbol' => '₽',
                'phone_code' => '+7',
                'flag_emoji' => '🇷🇺',
                'flag_svg' => 'https://flagcdn.com/ru.svg',
                'languages' => json_encode(['rus']),
                'tld' => '.ru',
                'latitude' => 61.5240,
                'longitude' => 105.3188,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 28,
                'metadata' => json_encode(['area' => 17098242, 'population' => 145912025]),
            ],
            // South Africa
            [
                'code' => 'ZA',
                'code_alpha3' => 'ZAF',
                'numeric_code' => '710',
                'name' => 'South Africa',
                'native_name' => json_encode(['eng' => 'South Africa', 'afr' => 'Suid-Afrika', 'zul' => 'iNingizimu Afrika']),
                'capital' => 'Pretoria',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'currency_code' => 'ZAR',
                'currency_name' => 'South African Rand',
                'currency_symbol' => 'R',
                'phone_code' => '+27',
                'flag_emoji' => '🇿🇦',
                'flag_svg' => 'https://flagcdn.com/za.svg',
                'languages' => json_encode(['eng', 'afr', 'zul']),
                'tld' => '.za',
                'latitude' => -30.5595,
                'longitude' => 22.9375,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 29,
                'metadata' => json_encode(['area' => 1221037, 'population' => 59308690]),
            ],
            // Argentina
            [
                'code' => 'AR',
                'code_alpha3' => 'ARG',
                'numeric_code' => '032',
                'name' => 'Argentina',
                'native_name' => json_encode(['spa' => 'Argentina']),
                'capital' => 'Buenos Aires',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'ARS',
                'currency_name' => 'Argentine Peso',
                'currency_symbol' => '$',
                'phone_code' => '+54',
                'flag_emoji' => '🇦🇷',
                'flag_svg' => 'https://flagcdn.com/ar.svg',
                'languages' => json_encode(['spa']),
                'tld' => '.ar',
                'latitude' => -38.4161,
                'longitude' => -63.6167,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 30,
                'metadata' => json_encode(['area' => 2780400, 'population' => 45195774]),
            ],

            // Colombia
            [
                'code' => 'CO',
                'code_alpha3' => 'COL',
                'numeric_code' => '170',
                'name' => 'Colombia',
                'native_name' => json_encode(['spa' => 'Colombia']),
                'capital' => 'Bogotá',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'COP',
                'currency_name' => 'Colombian Peso',
                'currency_symbol' => '$',
                'phone_code' => '+57',
                'flag_emoji' => '🇨🇴',
                'flag_svg' => 'https://flagcdn.com/co.svg',
                'languages' => json_encode(['spa']),
                'tld' => '.co',
                'latitude' => 4.5709,
                'longitude' => -74.2973,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 31,
                'metadata' => json_encode(['area' => 1141748, 'population' => 50882891]),
            ],

            // Peru
            [
                'code' => 'PE',
                'code_alpha3' => 'PER',
                'numeric_code' => '604',
                'name' => 'Peru',
                'native_name' => json_encode(['spa' => 'Perú']),
                'capital' => 'Lima',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'PEN',
                'currency_name' => 'Peruvian Sol',
                'currency_symbol' => 'S/',
                'phone_code' => '+51',
                'flag_emoji' => '🇵🇪',
                'flag_svg' => 'https://flagcdn.com/pe.svg',
                'languages' => json_encode(['spa']),
                'tld' => '.pe',
                'latitude' => -9.19,
                'longitude' => -75.0152,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 32,
                'metadata' => json_encode(['area' => 1285216, 'population' => 32971854]),
            ],

            // Egypt
            [
                'code' => 'EG',
                'code_alpha3' => 'EGY',
                'numeric_code' => '818',
                'name' => 'Egypt',
                'native_name' => json_encode(['ara' => 'مصر']),
                'capital' => 'Cairo',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'currency_code' => 'EGP',
                'currency_name' => 'Egyptian Pound',
                'currency_symbol' => '£',
                'phone_code' => '+20',
                'flag_emoji' => '🇪🇬',
                'flag_svg' => 'https://flagcdn.com/eg.svg',
                'languages' => json_encode(['ara']),
                'tld' => '.eg',
                'latitude' => 26.8206,
                'longitude' => 30.8025,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 33,
                'metadata' => json_encode(['area' => 1002450, 'population' => 102334404]),
            ],

            // Nigeria
            [
                'code' => 'NG',
                'code_alpha3' => 'NGA',
                'numeric_code' => '566',
                'name' => 'Nigeria',
                'native_name' => json_encode(['eng' => 'Nigeria']),
                'capital' => 'Abuja',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'NGN',
                'currency_name' => 'Nigerian Naira',
                'currency_symbol' => '₦',
                'phone_code' => '+234',
                'flag_emoji' => '🇳🇬',
                'flag_svg' => 'https://flagcdn.com/ng.svg',
                'languages' => json_encode(['eng']),
                'tld' => '.ng',
                'latitude' => 9.082,
                'longitude' => 8.6753,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 34,
                'metadata' => json_encode(['area' => 923768, 'population' => 206139589]),
            ],

            // Kenya
            [
                'code' => 'KE',
                'code_alpha3' => 'KEN',
                'numeric_code' => '404',
                'name' => 'Kenya',
                'native_name' => json_encode(['eng' => 'Kenya', 'swa' => 'Kenya']),
                'capital' => 'Nairobi',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'KES',
                'currency_name' => 'Kenyan Shilling',
                'currency_symbol' => 'KSh',
                'phone_code' => '+254',
                'flag_emoji' => '🇰🇪',
                'flag_svg' => 'https://flagcdn.com/ke.svg',
                'languages' => json_encode(['eng', 'swa']),
                'tld' => '.ke',
                'latitude' => -0.0236,
                'longitude' => 37.9062,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 35,
                'metadata' => json_encode(['area' => 580367, 'population' => 53771296]),
            ],

            // Hong Kong
            [
                'code' => 'HK',
                'code_alpha3' => 'HKG',
                'numeric_code' => '344',
                'name' => 'Hong Kong',
                'native_name' => json_encode(['zho' => '香港', 'eng' => 'Hong Kong']),
                'capital' => 'Hong Kong',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'HKD',
                'currency_name' => 'Hong Kong Dollar',
                'currency_symbol' => '$',
                'phone_code' => '+852',
                'flag_emoji' => '🇭🇰',
                'flag_svg' => 'https://flagcdn.com/hk.svg',
                'languages' => json_encode(['zho', 'eng']),
                'tld' => '.hk',
                'latitude' => 22.3193,
                'longitude' => 114.1694,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 36,
                'metadata' => json_encode(['area' => 1104, 'population' => 7496981]),
            ],

            // United Arab Emirates
            [
                'code' => 'AE',
                'code_alpha3' => 'ARE',
                'numeric_code' => '784',
                'name' => 'United Arab Emirates',
                'native_name' => json_encode(['ara' => 'الإمارات العربية المتحدة']),
                'capital' => 'Abu Dhabi',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'AED',
                'currency_name' => 'United Arab Emirates Dirham',
                'currency_symbol' => 'د.إ',
                'phone_code' => '+971',
                'flag_emoji' => '🇦🇪',
                'flag_svg' => 'https://flagcdn.com/ae.svg',
                'languages' => json_encode(['ara']),
                'tld' => '.ae',
                'latitude' => 23.4241,
                'longitude' => 53.8478,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 37,
                'metadata' => json_encode(['area' => 83600, 'population' => 9890402]),
            ],

            // Thailand
            [
                'code' => 'TH',
                'code_alpha3' => 'THA',
                'numeric_code' => '764',
                'name' => 'Thailand',
                'native_name' => json_encode(['tha' => 'ประเทศไทย']),
                'capital' => 'Bangkok',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'THB',
                'currency_name' => 'Thai Baht',
                'currency_symbol' => '฿',
                'phone_code' => '+66',
                'flag_emoji' => '🇹🇭',
                'flag_svg' => 'https://flagcdn.com/th.svg',
                'languages' => json_encode(['tha']),
                'tld' => '.th',
                'latitude' => 15.87,
                'longitude' => 100.9925,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 38,
                'metadata' => json_encode(['area' => 513120, 'population' => 69799978]),
            ],

            // Indonesia
            [
                'code' => 'ID',
                'code_alpha3' => 'IDN',
                'numeric_code' => '360',
                'name' => 'Indonesia',
                'native_name' => json_encode(['ind' => 'Indonesia']),
                'capital' => 'Jakarta',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'IDR',
                'currency_name' => 'Indonesian Rupiah',
                'currency_symbol' => 'Rp',
                'phone_code' => '+62',
                'flag_emoji' => '🇮🇩',
                'flag_svg' => 'https://flagcdn.com/id.svg',
                'languages' => json_encode(['ind']),
                'tld' => '.id',
                'latitude' => -0.7893,
                'longitude' => 113.9213,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 39,
                'metadata' => json_encode(['area' => 1904569, 'population' => 273523615]),
            ],

            // Pakistan
            [
                'code' => 'PK',
                'code_alpha3' => 'PAK',
                'numeric_code' => '586',
                'name' => 'Pakistan',
                'native_name' => json_encode(['urd' => 'پاکستان', 'eng' => 'Pakistan']),
                'capital' => 'Islamabad',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'PKR',
                'currency_name' => 'Pakistani Rupee',
                'currency_symbol' => '₨',
                'phone_code' => '+92',
                'flag_emoji' => '🇵🇰',
                'flag_svg' => 'https://flagcdn.com/pk.svg',
                'languages' => json_encode(['urd', 'eng']),
                'tld' => '.pk',
                'latitude' => 30.3753,
                'longitude' => 69.3451,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 40,
                'metadata' => json_encode(['area' => 881912, 'population' => 220892340]),
            ],

            // Fiji
            [
                'code' => 'FJ',
                'code_alpha3' => 'FJI',
                'numeric_code' => '242',
                'name' => 'Fiji',
                'native_name' => json_encode(['eng' => 'Fiji', 'fij' => 'Viti']),
                'capital' => 'Suva',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'currency_code' => 'FJD',
                'currency_name' => 'Fijian Dollar',
                'currency_symbol' => '$',
                'phone_code' => '+679',
                'flag_emoji' => '🇫🇯',
                'flag_svg' => 'https://flagcdn.com/fj.svg',
                'languages' => json_encode(['eng', 'fij']),
                'tld' => '.fj',
                'latitude' => -17.7134,
                'longitude' => 178.065,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 41,
                'metadata' => json_encode(['area' => 18272, 'population' => 896445]),
            ],

            // Turkey
            [
                'code' => 'TR',
                'code_alpha3' => 'TUR',
                'numeric_code' => '792',
                'name' => 'Turkey',
                'native_name' => json_encode(['tur' => 'Türkiye']),
                'capital' => 'Ankara',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'TRY',
                'currency_name' => 'Turkish Lira',
                'currency_symbol' => '₺',
                'phone_code' => '+90',
                'flag_emoji' => '🇹🇷',
                'flag_svg' => 'https://flagcdn.com/tr.svg',
                'languages' => json_encode(['tur']),
                'tld' => '.tr',
                'latitude' => 38.9637,
                'longitude' => 35.2433,
                'is_active' => true,
                'is_eu_member' => false,
                'display_order' => 42,
                'metadata' => json_encode(['area' => 783562, 'population' => 84339067]),
            ],
        ];

        foreach ($countries as $country) {
            $exists = DB::table('countries')->where('code', $country['code'])->exists();

            if ($exists) {
                DB::table('countries')
                    ->where('code', $country['code'])
                    ->update(array_merge($country, ['updated_at' => now()]));
            } else {
                DB::table('countries')->insert(array_merge($country, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            }
        }
    }
}
