<?php

namespace Database\Seeders;

use App\Models\Timezone;
use DateTimeZone;
use Illuminate\Database\Seeder;

class TimezonesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $timezones = $this->getTimezoneData();

        foreach ($timezones as $timezone) {
            Timezone::updateOrCreate(
                ['name' => $timezone['name']],
                $timezone
            );
        }
    }

    /**
     * Get comprehensive timezone data.
     */
    private function getTimezoneData(): array
    {
        return [
            // UTC - Primary timezone (Display Order 0)
            [
                'name' => 'UTC',
                'abbreviation' => 'UTC',
                'abbreviation_dst' => null,
                'offset' => 0,
                'offset_dst' => null,
                'offset_formatted' => 'UTC+00:00',
                'uses_dst' => false,
                'display_name' => 'UTC (Coordinated Universal Time)',
                'city_name' => 'UTC',
                'region' => 'UTC',
                'is_primary' => true,
                'is_active' => true,
                'display_order' => 0,
            ],

            // America/North America - Popular US & Canada Timezones (Display Order 1-10)
            [
                'name' => 'America/New_York',
                'abbreviation' => 'EST',
                'abbreviation_dst' => 'EDT',
                'offset' => $this->calculateOffset('America/New_York', false),
                'offset_dst' => $this->calculateOffset('America/New_York', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/New_York', false)),
                'uses_dst' => true,
                'display_name' => 'Eastern Time (US & Canada)',
                'city_name' => 'New York',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'America/Chicago',
                'abbreviation' => 'CST',
                'abbreviation_dst' => 'CDT',
                'offset' => $this->calculateOffset('America/Chicago', false),
                'offset_dst' => $this->calculateOffset('America/Chicago', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Chicago', false)),
                'uses_dst' => true,
                'display_name' => 'Central Time (US & Canada)',
                'city_name' => 'Chicago',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'America/Denver',
                'abbreviation' => 'MST',
                'abbreviation_dst' => 'MDT',
                'offset' => $this->calculateOffset('America/Denver', false),
                'offset_dst' => $this->calculateOffset('America/Denver', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Denver', false)),
                'uses_dst' => true,
                'display_name' => 'Mountain Time (US & Canada)',
                'city_name' => 'Denver',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 3,
            ],
            [
                'name' => 'America/Los_Angeles',
                'abbreviation' => 'PST',
                'abbreviation_dst' => 'PDT',
                'offset' => $this->calculateOffset('America/Los_Angeles', false),
                'offset_dst' => $this->calculateOffset('America/Los_Angeles', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Los_Angeles', false)),
                'uses_dst' => true,
                'display_name' => 'Pacific Time (US & Canada)',
                'city_name' => 'Los Angeles',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 4,
            ],
            [
                'name' => 'America/Toronto',
                'abbreviation' => 'EST',
                'abbreviation_dst' => 'EDT',
                'offset' => $this->calculateOffset('America/Toronto', false),
                'offset_dst' => $this->calculateOffset('America/Toronto', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Toronto', false)),
                'uses_dst' => true,
                'display_name' => 'Toronto',
                'city_name' => 'Toronto',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 5,
            ],
            [
                'name' => 'America/Phoenix',
                'abbreviation' => 'MST',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('America/Phoenix', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Phoenix', false)),
                'uses_dst' => false,
                'display_name' => 'Arizona',
                'city_name' => 'Phoenix',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 6,
            ],
            [
                'name' => 'America/Anchorage',
                'abbreviation' => 'AKST',
                'abbreviation_dst' => 'AKDT',
                'offset' => $this->calculateOffset('America/Anchorage', false),
                'offset_dst' => $this->calculateOffset('America/Anchorage', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Anchorage', false)),
                'uses_dst' => true,
                'display_name' => 'Alaska',
                'city_name' => 'Anchorage',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 7,
            ],
            [
                'name' => 'Pacific/Honolulu',
                'abbreviation' => 'HST',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Pacific/Honolulu', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Pacific/Honolulu', false)),
                'uses_dst' => false,
                'display_name' => 'Hawaii',
                'city_name' => 'Honolulu',
                'region' => 'Pacific',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 8,
            ],

            // America/Latin America (Display Order 11-15)
            [
                'name' => 'America/Mexico_City',
                'abbreviation' => 'CST',
                'abbreviation_dst' => 'CDT',
                'offset' => $this->calculateOffset('America/Mexico_City', false),
                'offset_dst' => $this->calculateOffset('America/Mexico_City', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Mexico_City', false)),
                'uses_dst' => true,
                'display_name' => 'Mexico City',
                'city_name' => 'Mexico City',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 11,
            ],
            [
                'name' => 'America/Sao_Paulo',
                'abbreviation' => 'BRT',
                'abbreviation_dst' => 'BRST',
                'offset' => $this->calculateOffset('America/Sao_Paulo', false),
                'offset_dst' => $this->calculateOffset('America/Sao_Paulo', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Sao_Paulo', false)),
                'uses_dst' => true,
                'display_name' => 'Brasilia',
                'city_name' => 'São Paulo',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 12,
            ],
            [
                'name' => 'America/Buenos_Aires',
                'abbreviation' => 'ART',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('America/Buenos_Aires', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Buenos_Aires', false)),
                'uses_dst' => false,
                'display_name' => 'Buenos Aires',
                'city_name' => 'Buenos Aires',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 13,
            ],
            [
                'name' => 'America/Bogota',
                'abbreviation' => 'COT',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('America/Bogota', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Bogota', false)),
                'uses_dst' => false,
                'display_name' => 'Bogota',
                'city_name' => 'Bogota',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 14,
            ],
            [
                'name' => 'America/Lima',
                'abbreviation' => 'PET',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('America/Lima', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('America/Lima', false)),
                'uses_dst' => false,
                'display_name' => 'Lima',
                'city_name' => 'Lima',
                'region' => 'America',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 15,
            ],

            // Europe (Display Order 16-25)
            [
                'name' => 'Europe/London',
                'abbreviation' => 'GMT',
                'abbreviation_dst' => 'BST',
                'offset' => $this->calculateOffset('Europe/London', false),
                'offset_dst' => $this->calculateOffset('Europe/London', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/London', false)),
                'uses_dst' => true,
                'display_name' => 'London',
                'city_name' => 'London',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 16,
            ],
            [
                'name' => 'Europe/Paris',
                'abbreviation' => 'CET',
                'abbreviation_dst' => 'CEST',
                'offset' => $this->calculateOffset('Europe/Paris', false),
                'offset_dst' => $this->calculateOffset('Europe/Paris', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Paris', false)),
                'uses_dst' => true,
                'display_name' => 'Paris',
                'city_name' => 'Paris',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 17,
            ],
            [
                'name' => 'Europe/Berlin',
                'abbreviation' => 'CET',
                'abbreviation_dst' => 'CEST',
                'offset' => $this->calculateOffset('Europe/Berlin', false),
                'offset_dst' => $this->calculateOffset('Europe/Berlin', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Berlin', false)),
                'uses_dst' => true,
                'display_name' => 'Berlin',
                'city_name' => 'Berlin',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 18,
            ],
            [
                'name' => 'Europe/Rome',
                'abbreviation' => 'CET',
                'abbreviation_dst' => 'CEST',
                'offset' => $this->calculateOffset('Europe/Rome', false),
                'offset_dst' => $this->calculateOffset('Europe/Rome', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Rome', false)),
                'uses_dst' => true,
                'display_name' => 'Rome',
                'city_name' => 'Rome',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 19,
            ],
            [
                'name' => 'Europe/Madrid',
                'abbreviation' => 'CET',
                'abbreviation_dst' => 'CEST',
                'offset' => $this->calculateOffset('Europe/Madrid', false),
                'offset_dst' => $this->calculateOffset('Europe/Madrid', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Madrid', false)),
                'uses_dst' => true,
                'display_name' => 'Madrid',
                'city_name' => 'Madrid',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 20,
            ],
            [
                'name' => 'Europe/Amsterdam',
                'abbreviation' => 'CET',
                'abbreviation_dst' => 'CEST',
                'offset' => $this->calculateOffset('Europe/Amsterdam', false),
                'offset_dst' => $this->calculateOffset('Europe/Amsterdam', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Amsterdam', false)),
                'uses_dst' => true,
                'display_name' => 'Amsterdam',
                'city_name' => 'Amsterdam',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 21,
            ],
            [
                'name' => 'Europe/Stockholm',
                'abbreviation' => 'CET',
                'abbreviation_dst' => 'CEST',
                'offset' => $this->calculateOffset('Europe/Stockholm', false),
                'offset_dst' => $this->calculateOffset('Europe/Stockholm', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Stockholm', false)),
                'uses_dst' => true,
                'display_name' => 'Stockholm',
                'city_name' => 'Stockholm',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 22,
            ],
            [
                'name' => 'Europe/Brussels',
                'abbreviation' => 'CET',
                'abbreviation_dst' => 'CEST',
                'offset' => $this->calculateOffset('Europe/Brussels', false),
                'offset_dst' => $this->calculateOffset('Europe/Brussels', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Brussels', false)),
                'uses_dst' => true,
                'display_name' => 'Brussels',
                'city_name' => 'Brussels',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 23,
            ],
            [
                'name' => 'Europe/Moscow',
                'abbreviation' => 'MSK',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Europe/Moscow', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Moscow', false)),
                'uses_dst' => false,
                'display_name' => 'Moscow',
                'city_name' => 'Moscow',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 24,
            ],
            [
                'name' => 'Europe/Istanbul',
                'abbreviation' => 'TRT',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Europe/Istanbul', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Europe/Istanbul', false)),
                'uses_dst' => false,
                'display_name' => 'Istanbul',
                'city_name' => 'Istanbul',
                'region' => 'Europe',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 25,
            ],

            // Asia (Display Order 26-35)
            [
                'name' => 'Asia/Tokyo',
                'abbreviation' => 'JST',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Tokyo', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Tokyo', false)),
                'uses_dst' => false,
                'display_name' => 'Tokyo',
                'city_name' => 'Tokyo',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 26,
            ],
            [
                'name' => 'Asia/Shanghai',
                'abbreviation' => 'CST',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Shanghai', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Shanghai', false)),
                'uses_dst' => false,
                'display_name' => 'Beijing, Shanghai',
                'city_name' => 'Shanghai',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 27,
            ],
            [
                'name' => 'Asia/Hong_Kong',
                'abbreviation' => 'HKT',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Hong_Kong', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Hong_Kong', false)),
                'uses_dst' => false,
                'display_name' => 'Hong Kong',
                'city_name' => 'Hong Kong',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 28,
            ],
            [
                'name' => 'Asia/Singapore',
                'abbreviation' => 'SGT',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Singapore', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Singapore', false)),
                'uses_dst' => false,
                'display_name' => 'Singapore',
                'city_name' => 'Singapore',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 29,
            ],
            [
                'name' => 'Asia/Dubai',
                'abbreviation' => 'GST',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Dubai', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Dubai', false)),
                'uses_dst' => false,
                'display_name' => 'Dubai, Abu Dhabi',
                'city_name' => 'Dubai',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 30,
            ],
            [
                'name' => 'Asia/Kolkata',
                'abbreviation' => 'IST',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Kolkata', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Kolkata', false)),
                'uses_dst' => false,
                'display_name' => 'Mumbai, Kolkata, New Delhi',
                'city_name' => 'Kolkata',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 31,
            ],
            [
                'name' => 'Asia/Bangkok',
                'abbreviation' => 'ICT',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Bangkok', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Bangkok', false)),
                'uses_dst' => false,
                'display_name' => 'Bangkok, Hanoi',
                'city_name' => 'Bangkok',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 32,
            ],
            [
                'name' => 'Asia/Seoul',
                'abbreviation' => 'KST',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Seoul', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Seoul', false)),
                'uses_dst' => false,
                'display_name' => 'Seoul',
                'city_name' => 'Seoul',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 33,
            ],
            [
                'name' => 'Asia/Jakarta',
                'abbreviation' => 'WIB',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Jakarta', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Jakarta', false)),
                'uses_dst' => false,
                'display_name' => 'Jakarta',
                'city_name' => 'Jakarta',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 34,
            ],
            [
                'name' => 'Asia/Karachi',
                'abbreviation' => 'PKT',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Asia/Karachi', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Asia/Karachi', false)),
                'uses_dst' => false,
                'display_name' => 'Karachi',
                'city_name' => 'Karachi',
                'region' => 'Asia',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 35,
            ],

            // Pacific/Oceania (Display Order 36-38)
            [
                'name' => 'Pacific/Auckland',
                'abbreviation' => 'NZST',
                'abbreviation_dst' => 'NZDT',
                'offset' => $this->calculateOffset('Pacific/Auckland', false),
                'offset_dst' => $this->calculateOffset('Pacific/Auckland', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Pacific/Auckland', false)),
                'uses_dst' => true,
                'display_name' => 'Auckland, Wellington',
                'city_name' => 'Auckland',
                'region' => 'Pacific',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 36,
            ],
            [
                'name' => 'Australia/Sydney',
                'abbreviation' => 'AEST',
                'abbreviation_dst' => 'AEDT',
                'offset' => $this->calculateOffset('Australia/Sydney', false),
                'offset_dst' => $this->calculateOffset('Australia/Sydney', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Australia/Sydney', false)),
                'uses_dst' => true,
                'display_name' => 'Sydney, Melbourne',
                'city_name' => 'Sydney',
                'region' => 'Pacific',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 37,
            ],
            [
                'name' => 'Pacific/Fiji',
                'abbreviation' => 'FJT',
                'abbreviation_dst' => 'FJST',
                'offset' => $this->calculateOffset('Pacific/Fiji', false),
                'offset_dst' => $this->calculateOffset('Pacific/Fiji', true),
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Pacific/Fiji', false)),
                'uses_dst' => true,
                'display_name' => 'Fiji',
                'city_name' => 'Suva',
                'region' => 'Pacific',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 38,
            ],

            // Africa (Display Order 39-42)
            [
                'name' => 'Africa/Cairo',
                'abbreviation' => 'EET',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Africa/Cairo', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Africa/Cairo', false)),
                'uses_dst' => false,
                'display_name' => 'Cairo',
                'city_name' => 'Cairo',
                'region' => 'Africa',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 39,
            ],
            [
                'name' => 'Africa/Johannesburg',
                'abbreviation' => 'SAST',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Africa/Johannesburg', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Africa/Johannesburg', false)),
                'uses_dst' => false,
                'display_name' => 'Johannesburg',
                'city_name' => 'Johannesburg',
                'region' => 'Africa',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 40,
            ],
            [
                'name' => 'Africa/Lagos',
                'abbreviation' => 'WAT',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Africa/Lagos', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Africa/Lagos', false)),
                'uses_dst' => false,
                'display_name' => 'Lagos',
                'city_name' => 'Lagos',
                'region' => 'Africa',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 41,
            ],
            [
                'name' => 'Africa/Nairobi',
                'abbreviation' => 'EAT',
                'abbreviation_dst' => null,
                'offset' => $this->calculateOffset('Africa/Nairobi', false),
                'offset_dst' => null,
                'offset_formatted' => $this->formatOffset($this->calculateOffset('Africa/Nairobi', false)),
                'uses_dst' => false,
                'display_name' => 'Nairobi',
                'city_name' => 'Nairobi',
                'region' => 'Africa',
                'is_primary' => false,
                'is_active' => true,
                'display_order' => 42,
            ],
        ];
    }

    /**
     * Calculate timezone offset in seconds from UTC.
     */
    private function calculateOffset(string $timezoneName, bool $isDst = false): int
    {
        try {
            $timezone = new DateTimeZone($timezoneName);

            if ($isDst) {
                // Use July 1st to get DST offset (summer in Northern Hemisphere)
                $dateTime = new \DateTime('2024-07-01 12:00:00', $timezone);
            } else {
                // Use January 1st to get standard offset (winter in Northern Hemisphere)
                $dateTime = new \DateTime('2024-01-01 12:00:00', $timezone);
            }

            return $timezone->getOffset($dateTime);
        } catch (\Exception $e) {
            return 0;
        }
    }

    /**
     * Format offset in seconds to human-readable format (e.g., UTC+05:30, UTC-08:00).
     */
    private function formatOffset(int $offsetSeconds): string
    {
        $hours = floor(abs($offsetSeconds) / 3600);
        $minutes = floor((abs($offsetSeconds) % 3600) / 60);

        $sign = $offsetSeconds >= 0 ? '+' : '-';

        if ($minutes > 0) {
            return sprintf('UTC%s%02d:%02d', $sign, $hours, $minutes);
        }

        return sprintf('UTC%s%02d:00', $sign, $hours);
    }
}
